baseURL = 'https://millisec.co/'
languageCode = 'en-us'
title = 'Millisec, Inc.'
theme = 'hello-friend-ng'

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  homeSubtitle = "Providing information security and software services to government, finance, automotive and aerospace industries."

[params.logo]
    logoMark     = ">"
    logoText     = "$ whois millisec.co"

 [[params.social]]
  name = "email"
  url = "contact"

 [[params.social]]
  name = "gpg"
  url = "pgp-key"

  [params.footer]
    trademark = "2024 Millisec, Inc."

 [menu]
  [[menu.main]]
    identifier = "services"
    name       = "Services"
    url        = "/services"
    weight = 5
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    weight = 1
  [[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact"
    weight = 10